In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(2000)

I give the probability at result of softmax will be:
$$softmax(logits) = p$$

for example I give them value of p in case of we have only 6 word in total vocab:
    $$ p =\begin{bmatrix} 0.1 & 0.2 &0.4 &0.1 &0.0 &0.2 \end{bmatrix}$$

and we have the exact result is y :
$$y = \begin{bmatrix} 0 & 0 & 1 & 0 & 0 & 0\end{bmatrix}$$

because y is some constant :
$$changing\_weight\_q\_value\_by =  -\frac {\partial\left(p \right)}{\partial q}$$
$$changing\_weight\_q\_value\_by =  -\frac {\partial\left(softmax(logits) \right)}{\partial logits} \cdot \frac {\partial\left(logits \right)}{\partial q}$$

from definition of error it should be like:
$$Error = {\left(y - p\right)}^2$$

but we use this function for calculate error instead:
$$\mathcal{L} = - \sum_{i = 0}^{V} y_i \log_e \left(p_i\right)$$

call **"cross-entropy loss"**

from the value of y จะได้ว่าค่า $\mathcal{L}$ จะมีค่าเป็น 0 หาก $y = 0$
และ $$\frac{\partial\mathcal{L}}{\partial q} = 0 ; y_i = 0$$ ด้วย

from $$\frac{d}{dx} \log_a(x) = \frac {1} {x \log_e {a}} = \frac {1} {x \ln\left(a\right)}$$

if we want to decrease error by change some value that will be combine into p 
we will write it to :
$$ changing\_weight\_q\_value\_by = \frac {\partial\mathcal{L}}{\partial q}$$
$$ \frac {\partial\mathcal{L}}{\partial q} = \frac {\partial}{\partial q} \left(-\sum_{i = 0}^V \left( y_i \ln \left(p_i\right) \right)\right)$$


from the y array we found that the equation have the value only at $y_i = 1$ then we got 
$$ \frac {\partial\mathcal{L}}{\partial q} = -\sum_{i=0}^V\frac {\partial\left( y_i \ln(p_i)\right)}{\partial p_i} \cdot \frac{\partial p_i} {\partial q}$$

$$ \frac {\partial\mathcal{L}}{\partial q} = -\frac {y_i}{p_i \ln\left(e\right)} \cdot \frac{\partial p_i} {\partial q}$$

## Softmax derivation
---

from softmax equation:
$$p_i = softmax(z_i) = \frac{e^{z_i}}{\sum_{k = 0}^{V - 1} \left(e^{z_k}\right)}$$

**การหาอนุพันธ์ของ Softmax จะพิเศษกว่าขั้นตอนอื่นเนื่องจาก $softmax\left(z_i\right)$ ไม่ได้ขึ้นอยู่กับแค่ $z_i$ แต่จะขึ้นอยู่กับค่าของ logits ทุกตัว
ดังนั้น**

if $$logits = \begin{bmatrix}z_0&z_1&...&z_j&...&z_{V - 1}\end{bmatrix}$$

$$\frac{\partial p_i} {\partial z_m} = ?$$
if $m = \begin{matrix} 0, 1,..., V-1 \end{matrix}$

We start with :

$$\frac{d}{dz_m} \frac{U}{S} = \frac{U^\prime S - US^\prime}{S^2}$$



$$U = e^{z_i}$$
and 
$$S = \sum_{k=0}^S \left(e^{z_k}\right)$$

$$\frac {\partial U} {\partial z_m} = 
\begin{cases} 
    e^{z_i} & \text{if $i = m$}\\ 
    0 & \text {if $i \neq m$} 
\end{cases}$$
**Or**
$$\frac {\partial U} {\partial z_m} = e^{z_i}\delta_{i,m}$$

then in case of $i = m$ we got : 

$$\frac{\partial p_i}{\partial z_m} = \frac{e^{z_i} S - e^{2\cdot z_i}}{S^2}$$
$$\frac{\partial p_i}{\partial z_m} = \frac{e^{z_i}}{S} \cdot \frac{S - e^{z_i}}{S}$$

finally got
$$\frac{\partial p_i}{\partial z_m} = p_i \cdot \left(1 - p_i\right)$$

if $i \neq m$ :
$$
    \frac{\partial p_i}{\partial z_m} = \frac{0 \cdot S - e^{z_i}e^{z_m}}{V^2}
$$

$$
    \frac{\partial p_i}{\partial z_m} = -\frac{e^{z_i}e^{z_m}}{S^2}
$$


**Or**
$$\frac{\partial p_i}{\partial z_m} = p_i \cdot \left(\delta_{i,m} - p_i\right)$$


---

## Mixing up

We have
$$\frac{\partial p_i}{\partial z_m} = p_i \cdot \left(\delta_{i, m} - p_j\right)$$
และ loss function (cross-entropy) ต่อ 1 ตำแหน่ง:

$$\mathcal{L} = - \sum_{i = 0}^{V} y_i \log_e \left(p_i\right)$$

โดย y มักจะเป็น one-hot (แต่ derivation นี้ใช้ได้กับ distribution ด้วย)

#### 1.) เริ่ม chain rule

$$\frac {\partial \mathcal {L}} {\partial z_m} =
\sum_{j=0}^{V - 1} \frac{\partial \mathcal{L}}{\partial p_i} \cdot
\frac {\partial p_i}{\partial z_m}$$

หา $\frac {\partial \mathcal{L}}{\partial p_i}$:

$$\frac {\partial \mathcal{L}}{\partial p_i} = -\frac{y_i}{p_i}$$

แทนกลับเข้าไป :
$$\frac {\partial \mathcal {L}} {\partial z_m} =
\sum_{i=0}^{V - 1} \left(\left(-\frac{y_i}{p_i} \right)\cdot
p_i \cdot \left(\delta_{i, m} - p_i\right)\right)

ตัด $p_i$ ทิ้ง :
$$\frac {\partial \mathcal {L}} {\partial z_m} =
\sum_{j=0}^{V - 1} \left(-{y_i}  \cdot \left(\delta_{i, m} - p_i\right)\right)

#### 2.) แยกผลรวมออกเป็น 2 ก้อน (นี่คือจุดที่ "เคสอื่น ๆ" จะถูกกินรวม)

$$-\sum_i y_i\left(\delta_{i, m} - p_m\right) = - \sum_i y_i \delta_{i, m} + \sum_i y_i p_m$$

สังเกตว่า $p_m$ ไม่ขึ้นกับ $i$ (สำหรับการ sum ตาม $i$) จึงสามารถดึงออกมาจากผลรวมได้:

$$ \frac {\partial \mathcal{L}} {\partial z_m} = -\sum_i y_i \delta_{i, m} + p_m \sum_i y_i$$

#### 3.) ประเมินผลรวมของ $\sum_i y_i \delta_{i,m}$ และ $\sum_i y_i$

* $\sum_i y_i \delta_{i, m}$ : $\delta_{i, m}$ ทำหน้าที่ "เลือก" เฉพาะตำแหน่ง $i = m$ ดังนั้น : 
$$ \sum_i y_i \delta_{i, m} = y_m$$

* $\sum_i y_i$ : ไม่ว่า $y$ เป็น one-hot หรือจะเป็น probability distribution จะมีค่าผลรวมเท่ากับ 1 เสมอ ดังนั้น :
$$ \sum_i y_i = 1$$


#### 4.) สรุปออกมาเป็น $p-y$

แทนค่า : 
$$\frac{\partial \mathcal {L}} {\partial z_m} = -y_m + p_m \cdot 1 = p_m - y_m$$

ดังนั้นในรูป vector : 
$$\frac{\partial \mathcal {L}} {\partial \vec{z}} = \vec{p}- \vec{y}$$

---

## Learn from dummy

สมมุติในการเทรน LLM เราจะมีข้อความหนึ่งชุด แล้วตัดเป็นชิ้นยาว T = 8 tokens:
* ถ้าใน 1 step เราใช้ข้อความแค่ชิ้นเดียว -> Batch size $B = 1$
    * input shape: (1, 8)
    * model จะทำนาย next-token 8 ตำแหน่ง
    * จำนวน token ที่ฝึกต่อ step = $B \cdot T = 8$ 

ตัวอย่าง batch จริง ๆ (หลายชิ้นพร้อมกัน)

สมมติเราเตรียมชิ้นข้อความ (แต่ละชิ้นยาว 8 tokens) ได้ 4 ชิ้น : 
* Step หนึ่งใช้ 4 ชิ้นพร้อมกัน -> Batch size $B = 4$
    * input shape: (4, 8)
    * จำนวน token ที่ฝึกต่อ step = $4 \cdot 8 = 32$

**ผลที่ได้คือ** : gradient ที่ได้ต่อ step จะมีความนิ่งขึ้น เพราะมาจากตัวอย่างที่มากขึ้น


* ตอนที่เราทำการเทรนทีละ Sequence หรือ ฺ$B = 1$ ใช้สมการเดิมได้ไม่มีปัญหา

* แต่ถ้าเอา 32 sequence มารวมกันเป็น batch -> $B = 32$

ทำให้ shape ที่ได้เป็น : 

* logits $Z: (B, T, V)$
* probs $P: (B, T, V)$
* targets $Y: (B, T, V)$ (one-hot) หรือ (B, T)(index)

---

ทำให้ตอนคิด Loss function จะต้องคิดเป็นค่าเฉลี่ย (mean) (เป็นที่นิยมใช้) แล้วได้สมการเป็น

$$\mathcal {L} = \frac {1} {B \cdot T} \sum_{b=1}^B \sum_{t=1}^T \left(-ln \left(p_{b, t, y_{b,t}}\right)\right)$$

แล้วทำให้ gradient มี factor $\frac {1} {B \cdot T}$ ติดมาด้วย : 

$$\frac{\partial \mathcal{L}} {\partial \vec{Z}} = \frac{\vec{P} - \vec{Y}}{B \cdot T} $$

In [3]:
def softmax(x, axis = -1):

    # หาค่ามากสุดตามแนวแกนที่เลือกมาแล้วหักลบกับแต่ละค่าในแมทริกส์
    # axis = -1 : [1, 2, 3], [4, 5, 6] -> (2, 3) shape 
    # ได้คำตอบเป็น [[3], [6]] ที่เป็นค่ามากสุดแต่ละค่าตามแนวแกน X
    x = x - np.max(x, axis = axis, keepdims=True)
    e = np.exp(x)
    return e / np.sum(e, axis = axis, keepdims = True)

### 1) for example Vocab มี 7 ตัว


In [40]:

vocab = ["<PAD>", "I", "You", "love", "a", "cat", "dog"]

มีทั้งหมด 2 ประโยค (Batch size $B = 2$)

In [ ]:
sentenceA = "I love a cat"
sentenceB = "You love a dog"

เราจะตั้ง sequence length ที่ใช้เทรนเป็น $T = 3$ (เอาแค่ 3 ตัวแรกเป็น input)

### 2 สร้าง X (input) และ Y (output) ด้วยการเลื่อนไปทางซ้าย 1 ระดับ 

In [54]:
X_a = [1, 3, 4]
Y_a = [3, 4, 5]

X_b = [2, 3, 4]
Y_b = [3, 4, 6]

### 3) เขียนเป็น Matrix (B, T)

In [55]:
X = np.array([X_a, X_b]);
Y = np.array([Y_a, Y_b]);

### 4) Model ให้ logits ออกมาเป็น (B, T, V)

$Z$ หรือ logits หมายถึงคะแนนดิบก่อน softmax
$$ Z \in \mathbb{R}^{2 \times 3 \times 7}$$
ในกรณีนี้
* มี ฺBatch size = 2 
* มี token size = 3 
* มี Vocab size (V) = 7


In [56]:
Z_0 = np.array([
    [-1, .2, -.3, 2.5, .1, -.7, 0.1],
    [-.4, -.2, -.5, .1, 2.2, 0, 0.1],
    [-.8, -.3, -.2, 0, .4, 2.6, 0.1]
    ])



In [57]:
Z_1 = np.array([
    [-1.1, -.1, 0, 2.3, .2, -.6, .1], 
    [-.5, -.3, -.4, .2, 2.4, -.1, .1],
    [-.9, -.4, -.1, .1, .3,.1, 2.5]
    ])

In [58]:
Z = np.array([Z_0, Z_1])
Z.shape

(2, 3, 7)

### 5) softmax ให้ได้รูปแบบ $P (B, T, V)$

In [59]:
P = softmax(Z)
print(P)

[[[0.02136409 0.07093128 0.043022   0.70748156 0.06418128 0.02883851
   0.06418128]
  [0.04677434 0.0571303  0.04232317 0.07711784 0.6297574  0.06977911
   0.07711784]
  [0.02356257 0.0388481  0.04293379 0.05243945 0.07823047 0.70603106
   0.05795456]]

 [[0.02206303 0.05997354 0.06628102 0.66109895 0.08095582 0.03637579
   0.07325185]
  [0.03727391 0.04552646 0.04119404 0.07506044 0.6774215  0.05560614
   0.0679175 ]
  [0.02293839 0.03781901 0.05105032 0.062353   0.07615813 0.062353
   0.68732815]]]


In [60]:
P.shape

(2, 3, 7)

**Structure of P และทำไมถึงใช้วิธีการหยิบค่ามาคำนวณได้เลย**

current output of P consist of 2 batch (index = 0 of shape)
ความน่าจะเป็นของโทเคนที่จะออกถัดไปของแต่ละ x ใน index = 1 of shape 
* ยกตัวอย่างของ batch ที่ 1 (P[0]) เราจะได้ว่าผลการเดาโทเคนตัวต่อไปของคำว่า I คือ (love, มีค่าความน่าจะเป็น P[0, 0, 3] = 0.75600279) 
    - แต่จาก one hot Y vector คำตอบที่ถูกต้องจะเป็น $Y = \begin{bmatrix} 0 & 0 & 0 & 1 & 0 & 0 \end{bmatrix}$
    - จากสมการเต็ม
    $$ \mathcal{L} = \frac{1} {B \cdot T} \sum_{b=0}^{B-1} \sum_{t=0}^{T-1} y_t \ln \left(p_t\right)$$
    - แต่ที่ $Y_{t \neq ตำแหน่งคำตอบที่ถูกต้อง} = 0$ จึงทำให้สมการลดรูปเหลือ
    $$ \mathcal{L} = \frac{1} {B \cdot T} \sum_{b, t} - \ln \left(P[b, t, Y[b, T]]\right)$$

### 6) คิด loss ด้วย Y (target)

เพราะ Y เก็บเป็น id ไม่ใช่ one-hot ทำให้เราคิด cross-entropy แบบหยิบเฉพาะคำ

$$ \mathcal{L} = \frac{1} {B \cdot T} \sum_{b, t} -ln \left(P[b, t, Y[b, t]]\right)$$

ตัวอย่างการหยิบค่ามาคิด loss

* สำหรับ A ที่ $t=0$ : target คือ $Y[0, 0] = 3$ (love) -> ใช้ค่า $P[0, 0, 3]$
* สำหรับ A ที่ $t=1$ : target คือ $Y[0, 1] = 4$ (a) -> ใช้ค่า $P[0, 1, 4]$ 

In [61]:
print(Y[0, 0])
print(P[0, 0, 3])

3
0.7074815607441387


In [62]:
B = P.shape[0] #total batch
T = P.shape[1] #total token in each step

totalLoss = 0
for b in range(B):
    for t in range(T):
        totalLoss += - np.log(P[b, t, Y[b, t]])
Loss = totalLoss / (B * T)

print("Loss ของรอบนี้คือ ", Loss)

Loss ของรอบนี้คือ  0.3891361962995475


In [64]:
B = 5
T = 6
V = 20

p = np.array([
    [.1, .2, .4, .1, 0, .1, 0], 
    [.1, .1, .2, 0, 5, .1, 0]]);
y = np.array([
    [0, 0, 1, 0, 0, 0, 0], 
    [0, 0, 0, 0, 0, 0, 1]
    ]);

$$\text{softmax}\left(\text{logits}\right) =  \frac{e^{logits_i-logits_{max}}}{\sum_{i = 0}^{V-1} e^{logits_i-logits_{max}}}$$

When $V$ is vocab size

### 7) แล้ว Gradient of logits จะเขียนได้ดังนี้

$$ \frac {\partial \mathcal {L}} {\partial Z} = \frac {P - Y_{onehot}} {B \cdot T} $$

วิธีด้านล่างนี้ผิด ==>

In [65]:
#find gradient of logits
B = P.shape[0]
T = P.shape[1]


# วิธีนี้ผิด
totalGradientOfLogits = 0

for b in range(B):
    for t in range(T):
        totalGradientOfLogits += P[b, t, Y[b, t]] - Y[b,t]

GradientOfLogits = totalGradientOfLogits / (B * T)
print ("Gradient of logits ในการคำนวณรอบนี้คือ ", GradientOfLogits)

Gradient of logits ในการคำนวณรอบนี้คือ  -3.488480230664544


#### วิธีที่ถูกต้อง ==>

In [66]:
# แบบใช้ one hot vector Y

B, T = Y.shape
V = P.shape[2]

Y_onehot = np.zeros((B, T, V), dtype=np.float64)
Y_onehot[np.arange(B)[:, None], np.arange(T)[None, :], Y] = 1.0

print("ได้ Onehot of Y เป็น")
print(Y_onehot)

ได้ Onehot of Y เป็น
[[[0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [67]:
GradientOfLogits = (P - Y_onehot) / (B * T)

print("แล้วได้ Gradient of logits เป็น ")
print(GradientOfLogits)

แล้วได้ Gradient of logits เป็น 
[[[ 0.00356068  0.01182188  0.00717033 -0.04875307  0.01069688
    0.00480642  0.01069688]
  [ 0.00779572  0.00952172  0.00705386  0.01285297 -0.0617071
    0.01162985  0.01285297]
  [ 0.00392709  0.00647468  0.00715563  0.00873991  0.01303841
   -0.04899482  0.00965909]]

 [[ 0.00367717  0.00999559  0.01104684 -0.05648351  0.01349264
    0.00606263  0.01220864]
  [ 0.00621232  0.00758774  0.00686567  0.01251007 -0.05376308
    0.00926769  0.01131958]
  [ 0.00382306  0.00630317  0.00850839  0.01039217  0.01269302
    0.01039217 -0.05211198]]]


จะเห็นได้ว่า gradient ของ lost function และ softmax (gradient ของ logits) $\frac {\partial \mathcal {L} } {\partial P} \cdot \frac {\partial P} {\partial Z}$ รวมกันมีมิติ เท่ากับ logits

$$\frac {\partial \mathcal {L}} {\partial Z} \in \mathbb {R} ^ {B \times T \times V}$$

Where 
* $B$ is batch size
* $T$ is token size
* $V$ is vocab size

In [68]:
# index target method

B, T, V = P.shape

dZ = P.copy()
dZ /= (B * T)

# subtract 1/(B * T) at the true class indices

dZ[np.arange(B)[:, None], np.arange(T)[None, :], Y] -= 1.0 / (B * T)

print (dZ.shape)
print(dZ)

(2, 3, 7)
[[[ 0.00356068  0.01182188  0.00717033 -0.04875307  0.01069688
    0.00480642  0.01069688]
  [ 0.00779572  0.00952172  0.00705386  0.01285297 -0.0617071
    0.01162985  0.01285297]
  [ 0.00392709  0.00647468  0.00715563  0.00873991  0.01303841
   -0.04899482  0.00965909]]

 [[ 0.00367717  0.00999559  0.01104684 -0.05648351  0.01349264
    0.00606263  0.01220864]
  [ 0.00621232  0.00758774  0.00686567  0.01251007 -0.05376308
    0.00926769  0.01131958]
  [ 0.00382306  0.00630317  0.00850839  0.01039217  0.01269302
    0.01039217 -0.05211198]]]


## Padding and loss mark

Loss mark คือ ตัวกรองว่า ตำแหน่งไหน ใน Sequence ที่เราจะนำไปคิด Loss และตำแหน่งไหน ไม่คิด  

**โดยจะใช้ตอนคำนวณ Loss เท่านั้นไม่คิดใน attention**

**Loss mark ใช้ทำอะไรบ้าง**

1. กัน PAD ไม่ให้ถูกเอาไปคิด loss

เวลา batch ประโยคยาวไม่เท่ากัน เราต้อง pad ให้ยาวเท่ากันเช่นการใส่ <PAD> = id 0 ตำแหน่งที่ PAD ไม้ใช่ข้อมูลจริง -> *ไม่ควรคิด loss*

2. Instruction tuning / Chat format

เรามัก ไม่อยากให้โมเดลเรียนรู้การทวน Prompt เราอยากให้เรียนเฉพาะคำตอบ (assistanct)
เลย mark ตำแหน่ง prompt = 0 และคำตอบ = 1

3. Ignore special tokens

เช่น <BOS> <SEP> หรือบางคำที่ไม่อยากให้ train


### Shape of loss mark 

loss mark มักจะมี shape เดียวกับ target tokens:
* $Y \in \mathbb {R} ^ {B \times T}$
* $loss\_mark \in \left\{1, 0\right\} ^ {B \times T}$ และมีค่าข้างในแค่ 0 และ 1

### สูตรคำนวณ loss แบบมี mask 

$$\mathcal {L} = \frac {\sum_{b,t} m_{b, t} \cdot \left(-log \left( P [b, t, Y[b, t]]\right)\right)} {\sum_{b, t} m_{b, t}}$$

### 1) Demo data
---
* token ที่เป็น system / user / prompt &rarr; mask = 0
* token ที่เป็น assistant response &rarr; mask = 1

ในขั้นตอนของการ tokenization ถ้ารู้ช่วง index ของ assistant เช่นช่วง $\left[ start : end \right)$ สามารถใช้คำสั่ง

In [69]:
#focus ที่ mask y

start = 0;
end = 2
loss_mask = np.zeros((B, T), dtype=np.float64)
loss_mask[b, start: end] = 1

print(loss_mask)

[[0. 0. 0.]
 [1. 1. 0.]]


In [70]:
B = 2
T = 4

In [71]:
X_mask1 = [1, 3, 4, 5] #I love a cat
Y_mask1 = [3, 4, 5, 0] #love a cat <PAD>

X_mask2 = [3, 4, 5, 0] #love a cat <PAD>
Y_mask2 = [4, 5, 0, 0] #cat <PAD> <PAD>

pad_id = 0;

In [72]:
Y = np.array([Y_mask1, Y_mask2]);
print(Y)

[[3 4 5 0]
 [4 5 0 0]]


loss_mask (1 เฉพาะตำแหน่งที่ไม่ใช่ PAD)

> * m คือ loss mask matrix
> * M คือ จำนวน token ทั้งหมดที่จะถูกนำไปเทรน

กติกา: ตำแหน่ง Y == pad_id -> mask = 0 (ไม่คิด loss)
ตำแหน่งที่ Y != pad_id -> mask = 1 (คิด loss)

จำนวนตำแหน่งที่คิด loss ทั้งหมด
$$M = \sum loss\_mask = 4$$


In [73]:

# ถ้าค่าใน Y ไม่เท่ากับ pad_id (0) จะได้เป็นค่า 1 นอกนั้น 0
m = (Y != pad_id).astype(np.float64) # (B, T)
M = m.sum()

print(m)

[[1. 1. 1. 0.]
 [1. 1. 0. 0.]]


สมมุติ logits $ Z \in \mathbb {R} ^ {B \times T \times V}$ 

**ปรกติเลขที่ได้จะไม่ใช่ 0 ล้วนแต่เพื่อให้ง่ายต่อการมองเห็นภาพ โดยปรกติแล้วตำแหน่งของเลขที่มากที่สุดจะหมายถึง ความน่าจะเป็นที่ token ถัดไปจะออก**

In [74]:
Z = np.zeros((B, T, V), dtype=np.float64)
 
Z[0, 0, 3] = 3.0
Z[0, 1, 4] = 1.0 # (b0, t1) target 4
Z[0, 2, 5] = 2.0 # (b0, t2) target 5
Z[0, 0, 4] = 4
Z[1, 1, 5] = 0.5 # (b1, t1) target 5

print(Z)

[[[0.  0.  0.  3.  4.  0.  0. ]
  [0.  0.  0.  0.  1.  0.  0. ]
  [0.  0.  0.  0.  0.  2.  0. ]
  [0.  0.  0.  0.  0.  0.  0. ]]

 [[0.  0.  0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0.  0.5 0. ]
  [0.  0.  0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0.  0.  0. ]]]


นำค่า logits ที่ได้ไปหาค่าความน่าจะเป็น $P$ โดยใช้ softmax function &rarr;

In [75]:
P = softmax(Z)
print(P)

[[[0.01254962 0.01254962 0.01254962 0.25206586 0.68518604 0.01254962
   0.01254962]
  [0.1147015  0.1147015  0.1147015  0.1147015  0.311791   0.1147015
   0.1147015 ]
  [0.07468786 0.07468786 0.07468786 0.07468786 0.07468786 0.55187282
   0.07468786]
  [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
   0.14285714]]

 [[0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
   0.14285714]
  [0.13074081 0.13074081 0.13074081 0.13074081 0.13074081 0.21555515
   0.13074081]
  [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
   0.14285714]
  [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
   0.14285714]]]


one-hot matrix Y &rarr; Y_onehot

In [76]:
Y_onehot = np.zeros((B, T, V), dtype=np.float64)
Y_onehot[np.arange(B)[:, None], np.arange(T)[None, :], Y] = 1.0

print(Y_onehot)

[[[0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]]]


In [77]:
print(vocab)

['<PAD>', 'I', 'You', 'love', 'a', 'cat', 'dog']


[[[0. 0. 0. 0. 1. 0.] >> คำต่อไปที่จะออกคือ "a"  
  [0. 0. 0. 0. 0. 1.] >> คำต่อไปที่จะออกคือ "cat"  
  [1. 0. 0. 0. 0. 0.]] >> คำต่อไปที่จะออกคือ "PAD"  

 [[0. 0. 0. 0. 0. 1.]  
  [1. 0. 0. 0. 0. 0.]  
  [1. 0. 0. 0. 0. 0.]]]  

In [78]:

#สร้าง array ใหม่โดยใช้วิธีการหยิบค่าจาก p_correct โดยที่

#p_correct[0, 0] หมายถึงเข้าไปหยิบค่ามาจาก P[0, 0, Y[0, 0]]
#p_correct[1, 2] หมายถึงเข้าไปหยิบค่ามาจาก P[1, 2, Y[1, 2]]
p_correct = P[np.arange(B)[:, None], np.arange(T)[None, :], Y] # (B, T)
print("p_correct ->\n", p_correct);

nll = -np.log(p_correct + 1e-12) # เลข 1e-12 ใส่มาเพื่อกัน log (0)
loss = (nll * m).sum() / max(M, 1)
print("loss : ", loss)

p_correct ->
 [[0.25206586 0.311791   0.55187282 0.14285714]
 [0.14285714 0.21555515 0.14285714 0.14285714]]
loss :  1.3236746715423062


#### วิธีการคำนวน A : $\frac{\partial \mathcal {L} } {\partial Z} = \frac {\left(P - Y_{one-hot}\right)\ *\ m[:, :, None] } {M}$

In [79]:
dZ = (P - Y_onehot) * m[:, :, None]
dZ = dZ / max(M, 1)
print (dZ)

[[[ 0.00250992  0.00250992  0.00250992 -0.14958683  0.13703721
    0.00250992  0.00250992]
  [ 0.0229403   0.0229403   0.0229403   0.0229403  -0.1376418
    0.0229403   0.0229403 ]
  [ 0.01493757  0.01493757  0.01493757  0.01493757  0.01493757
   -0.08962544  0.01493757]
  [-0.          0.          0.          0.          0.
    0.          0.        ]]

 [[ 0.02857143  0.02857143  0.02857143  0.02857143 -0.17142857
    0.02857143  0.02857143]
  [ 0.02614816  0.02614816  0.02614816  0.02614816  0.02614816
   -0.15688897  0.02614816]
  [-0.          0.          0.          0.          0.
    0.          0.        ]
  [-0.          0.          0.          0.          0.
    0.          0.        ]]]


In [80]:
print("loss_mark m = \n", m) 
print("M = ", M)
print("masked_loss = ", loss)

print("\ndZ[0, 0, :] =", dZ[0, 0, :])
print("dZ[0, 1, :] =", dZ[0,1,:])
print("dZ[0, 2, :] =", dZ[0,2,:])  # PAD target -> mask=0 -> should be all zeros

loss_mark m = 
 [[1. 1. 1. 0.]
 [1. 1. 0. 0.]]
M =  5.0
masked_loss =  1.3236746715423062

dZ[0, 0, :] = [ 0.00250992  0.00250992  0.00250992 -0.14958683  0.13703721  0.00250992
  0.00250992]
dZ[0, 1, :] = [ 0.0229403  0.0229403  0.0229403  0.0229403 -0.1376418  0.0229403
  0.0229403]
dZ[0, 2, :] = [ 0.01493757  0.01493757  0.01493757  0.01493757  0.01493757 -0.08962544
  0.01493757]


จะเห็นได้ว่าตำแหน่งที่ถูก mask ไว้ (Y = PAD) &rarr; $m = 0$  &rarr; $dZ = 0$  

ทำให้ทั้ง Vocab &rarr; weight upstream ไม่โดน Update จากตำแหน่งนั้นเลย

#### วิธีการคำนวณ B : index trick

In [81]:
Y

array([[3, 4, 5, 0],
       [4, 5, 0, 0]])

In [82]:
dZ = P.copy()
B, T, V = P.shape
M = m.sum()


print("P = \n", P)


# subtract 1 at the true class indices
dZ[np.arange(B)[:, None], np.arange(T)[None, :], Y ] -= 1.0

# apply mask and normalize
dZ *= m[:, :, None]
dZ /= max(M, 1) # avoid division by zero
print("\n\ndZ => \n", dZ)

P = 
 [[[0.01254962 0.01254962 0.01254962 0.25206586 0.68518604 0.01254962
   0.01254962]
  [0.1147015  0.1147015  0.1147015  0.1147015  0.311791   0.1147015
   0.1147015 ]
  [0.07468786 0.07468786 0.07468786 0.07468786 0.07468786 0.55187282
   0.07468786]
  [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
   0.14285714]]

 [[0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
   0.14285714]
  [0.13074081 0.13074081 0.13074081 0.13074081 0.13074081 0.21555515
   0.13074081]
  [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
   0.14285714]
  [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
   0.14285714]]]


dZ => 
 [[[ 0.00250992  0.00250992  0.00250992 -0.14958683  0.13703721
    0.00250992  0.00250992]
  [ 0.0229403   0.0229403   0.0229403   0.0229403  -0.1376418
    0.0229403   0.0229403 ]
  [ 0.01493757  0.01493757  0.01493757  0.01493757  0.01493757
   -0.08962544  0.01493757]
  [-0.          0.          0.       

### ทำไมตอนใส่ loss mask เราใช้แค่ M ในการ normalize ไม่ใช่ B * T หรือ M * B * T

> เป้าหมายในการ normalize คือให้ loss / gradient เป็น average ต่อ 1 token ที่ถูก train ซึ่งจำนวน token ที่ถูก train คือ $M = \sum m$

**กันสับสน ตำแหน่งที่ถูก train จะมีค่าเท่ากับ 1 ใน loss mask matrix**

In [34]:
loss_mask = np.array([[1, 1, 0], [1, 0, 0]])
print(loss_mask)

[[1 1 0]
 [1 0 0]]


In [35]:
def lm_head_forward(H, W, b):
    #H: (T, d), W: (d, V), b: (V,)
    Z = H @ W + b # (T, V) probs
    P = softmax(Z, axis = 1) # (T, V) probs

    return Z, P

In [36]:
def lossAndSoftmaxBackward(y, p):
    return p - y

In [37]:
dlossBydz = lossAndSoftmaxBackward(y, p)
dlossBydz

array([[ 0.1,  0.2, -0.6,  0.1,  0. ,  0.1],
       [ 0.1,  0.1,  0.2,  0. ,  4. ,  0.1]])

## Use in another sheet

In [83]:
dZ

array([[[ 0.00250992,  0.00250992,  0.00250992, -0.14958683,
          0.13703721,  0.00250992,  0.00250992],
        [ 0.0229403 ,  0.0229403 ,  0.0229403 ,  0.0229403 ,
         -0.1376418 ,  0.0229403 ,  0.0229403 ],
        [ 0.01493757,  0.01493757,  0.01493757,  0.01493757,
          0.01493757, -0.08962544,  0.01493757],
        [-0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ]],

       [[ 0.02857143,  0.02857143,  0.02857143,  0.02857143,
         -0.17142857,  0.02857143,  0.02857143],
        [ 0.02614816,  0.02614816,  0.02614816,  0.02614816,
          0.02614816, -0.15688897,  0.02614816],
        [-0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ]]])